
# Documentation - https://github.com/dockur/windows
# https://www.youtube.com/watch?v=iNvJdzs8rw8


# http://localhost:8006/

networks:
  windows_network:
    name: windows_network
    external: false
    driver: bridge
    
volumes:
  windows_storage:
    name: windows_storage
    driver: local
  windows_network:
    name: windows_storage
    driver: local
    
services:
  windows:
    container_name: windows
    image: dockurr/windows
    restart: always
    environment:
      LANGUAGE: "Portuguese"
      REGION: "pt-BR"
      KEYBOARD: "pt-BR"
      USERNAME: "user"
      PASSWORD: ""
      RAM_SIZE: "16G"
      CPU_CORES: "8"
      VERSION: "11"
      DISK_SIZE: "256G"
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    stop_grace_period: 2m
    networks:
      - windows_network
    volumes:
      - "windows_storage:/storage"
      - "windows_network:/data"